function DatosBBQS4 = importfile2(workbookFile, sheetName, dataLines)
%IMPORTFILE2 Import data from a spreadsheet
%  DATOSBBQS4 = IMPORTFILE2(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DATOSBBQS4 = IMPORTFILE2(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DATOSBBQS4 = IMPORTFILE2(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DatosBBQS4 = importfile2("C:\Users\Marta\Documents\GitHub\TFM\Capitol carcteritzar nodes\Prova petit foc\Datos_BBQ.xlsx", "datos_QAire", [2, 48]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Sep-2020 13:34:35

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 48];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":E" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Column1", "Column2", "Column3", "Column4", "Column5"];
opts.SelectedVariableNames = ["Column1", "Column2", "Column3", "Column4", "Column5"];
opts.VariableTypes = ["datetime", "datetime", "double", "double", "double"];
opts = setvaropts(opts, 1, "InputFormat", "");

% Import the data
DatosBBQS4 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":E" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    DatosBBQS4 = [DatosBBQS4; tb]; %#ok<AGROW>
end

end