function DatosBBQ = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DATOSBBQ = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DATOSBBQ = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  DATOSBBQ = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DatosBBQ = importfile("C:\Users\Marta\Documents\GitHub\TFM\Capitol carcteritzar nodes\Prova petit foc\Datos_BBQ.xlsx", "datos_bmp", [2, 99]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Sep-2020 13:28:36

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 99];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Column1", "Column2", "Column3", "Column4"];
opts.SelectedVariableNames = ["Column1", "Column2", "Column3", "Column4"];
opts.VariableTypes = ["datetime", "Categorical", "double", "double"];
opts = setvaropts(opts, 1, "InputFormat", "");

% Import the data
DatosBBQ = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    DatosBBQ = [DatosBBQ; tb]; %#ok<AGROW>
end

end